In [3]:
from metpy.calc import virtual_temperature
from metpy.units import units

In [5]:
virtual_temperature([283, 293] * units.K, 12 * units('g/kg'))

<Quantity([285.03970883 295.11178335], 'kelvin')>

In [1]:
from metpy.calc import cape_cin, dewpoint_from_relative_humidity, parcel_profile
from metpy.units import units

# pressure
p = [1008., 1000., 950., 900., 850., 800., 750., 700., 650., 600.,
     550., 500., 450., 400., 350., 300., 250., 200.,
     175., 150., 125., 100., 80., 70., 60., 50.,
     40., 30., 25., 20.] * units.hPa
# temperature
T = [29.3, 28.1, 23.5, 20.9, 18.4, 15.9, 13.1, 10.1, 6.7, 3.1,
     -0.5, -4.5, -9.0, -14.8, -21.5, -29.7, -40.0, -52.4,
     -59.2, -66.5, -74.1, -78.5, -76.0, -71.6, -66.7, -61.3,
     -56.3, -51.7, -50.7, -47.5] * units.degC
# relative humidity
rh = [.85, .65, .36, .39, .82, .72, .75, .86, .65, .22, .52,
      .66, .64, .20, .05, .75, .76, .45, .25, .48, .76, .88,
      .56, .88, .39, .67, .15, .04, .94, .35] * units.dimensionless
# calculate dewpoint
Td = dewpoint_from_relative_humidity(T, rh)

In [3]:
# compture parcel temperature
prof = parcel_profile(p, T[0], Td[0]).to('degC')

In [2]:
import metpy._calc_mod as calc

In [2]:
# calculate surface based CAPE/CIN
cape_cin(p, T, Td, prof)

<Quantity([ 26.47667383  20.87471374   7.56165274   6.42289825  15.26182826
  10.85323559   8.76479619   7.85930825   0.57944499 -16.5979205
  -9.16443107  -9.90490512 -14.58503489 -32.8409952  -51.23729024
 -32.72822081 -42.59410132 -58.85968702 -69.38777    -71.44480445
 -75.52927546 -78.8275893  -79.28793824 -72.13425645 -73.04415021
 -64.15899891 -70.46374967 -75.70199744 -51.1557397  -56.39592478], 'degree_Celsius')>

In [1]:
import metpy._calc_mod as calc_mod
import numpy as np

In [2]:
T = np.array([283, 293, 303])

In [3]:
calc_mod.virtual_temperature(T, 0.012)

TypeError: virtual_temperature(): incompatible function arguments. The following argument types are supported:
    1. (temperature: numpy.ndarray[numpy.float64], mixing_ratio: numpy.ndarray[numpy.float64], epsilon: numpy.ndarray[numpy.float64]) -> object

Invoked with: array([283, 293, 303]), 0.012

In [8]:
T = np.array([283, 293, 303])
w = np.array([0.012, 0.012])
calc.virtual_temperature(T, w)

RuntimeError: pybind11::vectorize: incompatible size/dimension of inputs!

In [7]:
T = np.array([283, 293, 303])
w = 0.012
calc.virtual_temperature(T, w)

array([285.03933505, 295.11139636, 305.18345767])

In [5]:
T = 283
w = 1
e = 1.1
calc.virtual_temperature(T, w, e)

270.1363636363636

In [7]:
T = 283
w = 0.012
e = np.array([0.5, 0.622, 0.1])
calc.virtual_temperature(T, w, e)

array([286.35573123, 285.03933505, 313.20158103])

In [13]:
P = 1000
T = 25+273.15
calc_mod.saturation_mixing_ratio(P, T, phase='auto')

Total pressure must be greater than the saturation vapor pressure for liquid water to be in equilibrium.


nan

In [15]:
calc_mod.saturation_vapor_pressure(25+273.15, phase='liquid')

3162.345599110219

In [7]:
calc_mod.mixing_ratio(3162.345599110219, 98300, 0.621957)

epsilon:0.621957


0.020673654339825723

In [1]:
import metpy.calc as calc
import metpy._calc_mod as calc_mod
from metpy.units import units
import numpy as np

In [6]:
"""  Virtual temperature  """
T = np.array([
    [[290.0, 291.5, 289.0],
     [292.0, 290.5, 288.5],
     [291.0, 289.5, 290.0]],

    [[270.0, 271.0, 269.5],
     [273.16, 270.5, 268.0],
     [271.5, 269.0, 270.0]],

    [[230.0, 231.0, 229.5],
     [232.0, 230.5, 228.0],
     [231.5, 229.0, 230.0]]
]) * units.K
w = 12 * units('g/kg')
calc.virtual_temperature(T, w)

<Quantity([[[292.09016099 293.60097217 291.08295354]
  [294.1045759  292.59376472 290.57934981]
  [293.09736844 291.58655727 292.09016099]]

 [[271.94601196 272.95321941 271.44240823]
  [275.12878751 272.44961568 269.93159705]
  [273.45682314 270.93880451 271.94601196]]

 [[231.65771389 232.66492134 231.15411016]
  [233.67212879 232.16131762 229.64329899]
  [233.16852507 230.65050644 231.65771389]]], 'kelvin')>

In [7]:
"""  Saturation Vapor Pressure  """
calc.saturation_vapor_pressure(T, phase='liquid')

<Quantity([[[1916.7163842  2106.79447244 1798.50534655]
  [2173.71931631 1978.33417149 1741.83423515]
  [2041.67993905 1856.78654118 1916.7163842 ]]

 [[ 484.39990096  521.73121713  466.63949458]
  [ 611.2         502.75804213  416.77770463]
  [ 541.3371358   449.45992752  484.39990096]]

 [[  13.63784604   15.16427401   12.92830316]
  [  16.84452743   14.38264962   10.99649766]
  [  15.9843393    12.25251894   13.63784604]]], 'pascal')>

In [8]:
calc.saturation_vapor_pressure(T, phase='solid')

<Quantity([[[2253.33871265 2512.39570756 2094.31973463]
  [2604.5501384  2336.87349943 2018.68074238]
  [2423.19834602 2172.51358642 2253.33871265]]

 [[ 469.77095512  510.91379145  450.35277758]
  [ 611.2         489.94909721  396.40392933]
  [ 532.69243902  431.66876991  469.77095512]]

 [[   8.92145836   10.01873834    8.41552269]
  [  11.23962684    9.45539316    7.05250462]
  [  10.61296905    7.93623626    8.92145836]]], 'pascal')>

In [9]:
calc.saturation_vapor_pressure(T, phase='auto')

<Quantity([[[1916.7163842  2106.79447244 1798.50534655]
  [2173.71931631 1978.33417149 1741.83423515]
  [2041.67993905 1856.78654118 1916.7163842 ]]

 [[ 469.77095512  510.91379145  450.35277758]
  [ 611.2         489.94909721  396.40392933]
  [ 532.69243902  431.66876991  469.77095512]]

 [[   8.92145836   10.01873834    8.41552269]
  [  11.23962684    9.45539316    7.05250462]
  [  10.61296905    7.93623626    8.92145836]]], 'pascal')>

In [4]:
"""  Dewpoint  """
vapor_pressure = np.array([
    [[18.0, 17.5, 19.0],
     [16.0, 18.5, 20.0],
     [17.0, 19.5, 18.0]],

    [[8.0, 7.5, 9.0],
     [6.5, 8.5, 7.0],
     [7.0, 6.5, 8.0]],

    [[1.5, 1.0, 1.2],
     [1.8, 1.3, 1.1],
     [1.0, 1.4, 1.2]]
]) * units.hPa
calc.dewpoint(vapor_pressure)

<Quantity([[[ 15.85355802  15.41390259  16.70156739]
  [ 14.02520865  16.28260125  17.51121148]
  [ 14.96305512  17.11095128  15.85355802]]

 [[  3.7669019    2.85319338   5.45201425]
  [  0.85112357   4.63139441   1.8838606 ]
  [  1.8838606    0.85112357   3.7669019 ]]

 [[-17.93289083 -22.62788054 -20.54114153]
  [-15.75605783 -19.6125156  -21.54191601]
  [-22.62788054 -18.74581916 -20.54114153]]], 'degree_Celsius')>

In [5]:
calc.saturation_vapor_pressure(calc.dewpoint(vapor_pressure), phase='auto').to('hPa')

<Quantity([[[17.98914344 17.48988682 18.98750918]
  [15.99182702 18.48835102 19.985676  ]
  [16.99058156 19.4866176  17.98914344]]

 [[ 7.99571154  7.4956859   8.99570493]
  [ 6.49560036  8.49571923  6.99564701]
  [ 6.99564701  6.49560036  7.99571154]]

 [[ 1.25653603  0.7998148   0.97970598]
  [ 1.54057634  1.07110776  0.88925287]
  [ 0.7998148   1.16340105  0.97970598]]], 'hectopascal')>

In [7]:
"""  Dewpoint From Relative Humidity  """
temperature = np.array([
    [[25.0, 24.0, 26.0],
     [23.5, 25.0, 27.0],
     [24.5, 26.5, 25.5]],

    [[10.0, 9.0, 11.0],
     [8.5, 10.5, 9.5],
     [9.0, 8.0, 10.0]],

    [[-25.0, -26.0, -24.0],
     [-27.5, -25.0, -26.5],
     [-26.0, -27.0, -25.5]]
]) * units.degC
calc.dewpoint_from_relative_humidity(temperature, 50 * units.percent)

<Quantity([[[ 13.84289047  12.92652229  14.75875074]
  [ 12.46814986  13.84289047  15.67409632]
  [ 13.38476945  15.21648829  14.30088452]]

 [[  0.04790092  -0.8752534    0.97065233]
  [ -1.33697939   0.50932743  -0.41362633]
  [ -0.8752534   -1.7988034    0.04790092]]

 [[-32.44919221 -33.38171896 -31.51680062]
  [-34.78074478 -32.44919221 -33.84803049]
  [-33.38171896 -34.31437277 -32.9154392 ]]], 'degree_Celsius')>

In [8]:
relative_humidity = np.array([
    [[80, 75, 85],
     [70, 78, 82],
     [76, 80, 79]],

    [[65, 60, 68],
     [58, 62, 64],
     [61, 59, 63]],

    [[40, 35, 45],
     [30, 38, 42],
     [36, 39, 37]]
]) * units.percent
calc.dewpoint_from_relative_humidity(10.0 * units.degC, relative_humidity)

<Quantity([[[ 6.70438667  5.76888088  7.58957796]
  [ 4.77651367  6.33656145  7.06417363]
  [ 5.96030356  6.70438667  6.52150282]]

 [[ 3.71933719  2.5875667   4.36192135]
  [ 2.1113308   3.04994574  3.49930226]
  [ 2.82043433  2.35123618  3.27620269]]

 [[-2.98994992 -4.77185561 -1.39597137]
  [-6.79635891 -3.6775693  -2.33221745]
  [-4.39813121 -3.32984342 -4.03352297]]], 'degree_Celsius')>

In [4]:
"""  Saturation_Mixing_Ratio  """
P = 983 * units('hPa')
T = 25 * units('degC')
calc.saturation_mixing_ratio(P, T, phase='liquid').to('g/kg')

epsilon:0.621957


<Quantity(20.6736514, 'gram / kilogram')>

In [15]:
calc.specific_humidity_from_mixing_ratio(19 * units('g/kg'))

<Quantity(18.6457311, 'gram / kilogram')>

In [16]:
calc.specific_humidity_from_dewpoint(988 * units.hPa, 15 * units.degC).to('g/kg')

epsilon:0.621957


<Quantity(10.791541, 'gram / kilogram')>

In [5]:
w = np.array([0.019, 0.02])
calc_mod.specific_humidity_from_mixing_ratio(w)

array([0.01864573, 0.01960784])

In [6]:
P = np.array([98800, 80000])

calc_mod.specific_humidity_from_dewpoint(P, 15+273.15, "liquid")

array([0.01079154, 0.01334813])

In [11]:
calc.moist_air_gas_constant(1000 * units('g/kg'))

<Quantity(461.523116, 'joule / kelvin / kilogram')>

In [12]:
calc.moist_air_specific_heat_pressure(1000 * units('g/kg'))

<Quantity(1860.07801, 'joule / kelvin / kilogram')>

In [20]:
w = np.array([0.0, 0.02])

calc_mod.moist_air_gas_constant(w)

array([287.04749098, 290.53700347])

In [19]:
calc_mod.moist_air_specific_heat_pressure(w)

array([1020.9190425 , 1021.77445429])

In [2]:
"""  LCL  """
P = np.array([
    [[943.0, 1010.0, 1005.0],
     [1008.0, 1002.5, 995.0],
     [1000.0, 990.0, 985.0]],

    [[850.0, 845.0, 840.0],
     [835.0, 830.0, 825.0],
     [820.0, 815.0, 810.0]],

    [[700.0, 695.0, 690.0],
     [685.0, 680.0, 675.0],
     [670.0, 665.0, 660.0]]
])

T = np.array([
    [[33.0, 24.0, 26.0],
     [23.5, 25.0, 27.0],
     [24.5, 26.5, 25.5]],

    [[10.0, 9.0, 11.0],
     [8.5, 10.5, 9.5],
     [9.0, 8.0, 10.0]],

    [[-25.0, -26.0, -24.0],
     [-27.5, -25.0, -26.5],
     [-26.0, -27.0, -25.5]]
])

dewT = np.array([
    [[28.0, 22.0, 23.5],
     [21.5, 22.5, 24.5],
     [22.0, 24.0, 23.0]],

    [[7.5, 6.5, 8.0],
     [6.0, 8.0, 7.0],
     [6.5, 5.5, 7.0]],

    [[-27.0, -28.0, -26.0],
     [-29.0, -27.0, -28.0],
     [-28.0, -29.0, -27.5]]
])

calc.lcl(P * units.hPa, T * units.degC, dewT * units.degC)

(<Quantity([[[877.03354856 980.65222467 968.76852844]
   [978.68074571 966.28759905 959.19582964]
   [963.84179385 954.34073777 949.45131027]]
 
  [[818.26745788 813.37943203 802.58770619]
   [803.71584241 799.04854208 794.1626151 ]
   [789.31301026 784.42733391 773.83692518]]
 
  [[676.92475305 672.01898578 667.32373333]
   [667.86999884 657.58393401 658.17247326]
   [647.84551231 642.94267082 638.20969863]]], 'hectopascal')>,
 <Quantity([[[ 26.75919085  21.51680086  22.8916154 ]
   [ 21.01817361  21.89507951  23.88808225]
   [ 21.39679862  23.38981842  22.39329015]]
 
  [[  6.94427062   5.94741401   7.33213324]
   [  5.44896923   7.44265741   6.44581151]
   [  5.94737845   4.95050713   6.33586744]]
 
  [[-27.3648959  -28.36273895 -26.3670627 ]
   [-29.2708403  -27.36489775 -28.2724544 ]
   [-28.36274108 -29.36059224 -27.86381979]]], 'degree_Celsius')>)

In [4]:
calc.lcl_manual(P * units.hPa, T * units.degC, dewT * units.degC)


(<Quantity([[[877.03354856 980.65222467 968.76852844]
   [978.68074571 966.28759905 959.19582964]
   [963.84179385 954.34073777 949.45131027]]
 
  [[818.26745788 813.37943203 802.58770619]
   [803.71584241 799.04854208 794.1626151 ]
   [789.31301026 784.42733391 773.83692518]]
 
  [[676.92475305 672.01898578 667.32373333]
   [667.86999884 657.58393401 658.17247326]
   [647.84551231 642.94267082 638.20969863]]], 'hectopascal')>,
 <Quantity([[[ 26.75919085  21.51680086  22.8916154 ]
   [ 21.01817361  21.89507951  23.88808225]
   [ 21.39679862  23.38981842  22.39329015]]
 
  [[  6.94427062   5.94741401   7.33213324]
   [  5.44896923   7.44265741   6.44581151]
   [  5.94737845   4.95050713   6.33586744]]
 
  [[-27.3648959  -28.36273895 -26.3670627 ]
   [-29.2708403  -27.36489775 -28.2724544 ]
   [-28.36274108 -29.36059224 -27.86381979]]], 'degree_Celsius')>)

In [3]:
P_lcl, T_lcl = calc_mod.lcl(P * 100, T+273.15, dewT+273.15)
print(P_lcl/100, 'hPa')
print(T_lcl-273.15, 'degC')

TypeError: lcl(): incompatible function arguments. The following argument types are supported:
    1. (pressure: float, temperature: float, dewpoint: float) -> tuple[float, float]

Invoked with: array([[[ 94300., 101000., 100500.],
        [100800., 100250.,  99500.],
        [100000.,  99000.,  98500.]],

       [[ 85000.,  84500.,  84000.],
        [ 83500.,  83000.,  82500.],
        [ 82000.,  81500.,  81000.]],

       [[ 70000.,  69500.,  69000.],
        [ 68500.,  68000.,  67500.],
        [ 67000.,  66500.,  66000.]]]), array([[[306.15, 297.15, 299.15],
        [296.65, 298.15, 300.15],
        [297.65, 299.65, 298.65]],

       [[283.15, 282.15, 284.15],
        [281.65, 283.65, 282.65],
        [282.15, 281.15, 283.15]],

       [[248.15, 247.15, 249.15],
        [245.65, 248.15, 246.65],
        [247.15, 246.15, 247.65]]]), array([[[301.15, 295.15, 296.65],
        [294.65, 295.65, 297.65],
        [295.15, 297.15, 296.15]],

       [[280.65, 279.65, 281.15],
        [279.15, 281.15, 280.15],
        [279.65, 278.65, 280.15]],

       [[246.15, 245.15, 247.15],
        [244.15, 246.15, 245.15],
        [245.15, 244.15, 245.65]]])