In [1]:
import metpy.calc as calc
import metpy._calc_mod as calc_mod
from metpy.units import units
import numpy as np

# Moist Lapse Compare with Kintera

In [2]:
pres = np.array([100000.0000,  97127.4020,  94337.3222,  91627.3901,  88995.3035,
          86438.8262,  83955.7862,  81544.0740,  79201.6405,  76926.4957,
          74716.7068,  72570.3961,  70485.7404,  68460.9684,  66494.3600,
          64584.2443,  62728.9986,  60927.0466,  59176.8575,  57476.9442,
          55825.8627,  54222.2101,  52664.6239,  51151.7810,  49682.3959,
          48255.2204,  46869.0419,  45522.6828,  44214.9991,  42944.8799,
          41711.2461,  40513.0497,  39349.2726,  38218.9262,  37121.0501,
          36054.7115,  35019.0046,  34013.0494,  33035.9912,  32087.0000,
          31165.2694,  30270.0165,  29400.4806,  28555.9230,  27735.6261,
          26938.8931,  26165.0470,  25413.4304,  24683.4047,  23974.3497,
          23285.6630,  22616.7595,  21967.0709,  21336.0453,  20723.1465,
          20127.8538,  19549.6614,  18988.0782,  18442.6271,  17912.8445,
          17398.2805,  16898.4979,  16413.0720,  15941.5904,  15483.6526,
          15038.8695,  14606.8632,  14187.2667,  13779.7236,  13383.8875,
          12999.4222,  12626.0011,  12263.3068,  11911.0313,  11568.8753,
          11236.5480,  10913.7671,  10600.2585,  10295.7557,  10000.0000])
temp = 310.

### Metpy thermo

In [9]:
%%time

for i in range(10000):
    moist_temp_profile = calc.moist_lapse(pres * units.Pa, temp * units.K)

CPU times: user 17.9 s, sys: 211 ms, total: 18.1 s
Wall time: 18 s


### c++ Bakhshaii2013

In [7]:
%%time
for i in range(10000):
    moist_temp_profile = calc.moist_lapse_linfel(pres * units.Pa, temp * units.K)

CPU times: user 5.98 s, sys: 9.33 ms, total: 5.99 s
Wall time: 5.99 s


# Moist Lapse with multiple starting temperature provided

In [2]:
pres = np.array([100000.0000,  97127.4020,  94337.3222,  91627.3901,  88995.3035,
          86438.8262,  83955.7862,  81544.0740,  79201.6405,  76926.4957,
          74716.7068,  72570.3961,  70485.7404,  68460.9684,  66494.3600,
          64584.2443,  62728.9986,  60927.0466,  59176.8575,  57476.9442,
          55825.8627,  54222.2101,  52664.6239,  51151.7810,  49682.3959,
          48255.2204,  46869.0419,  45522.6828,  44214.9991,  42944.8799,
          41711.2461,  40513.0497,  39349.2726,  38218.9262,  37121.0501,
          36054.7115,  35019.0046,  34013.0494,  33035.9912,  32087.0000,
          31165.2694,  30270.0165,  29400.4806,  28555.9230,  27735.6261,
          26938.8931,  26165.0470,  25413.4304,  24683.4047,  23974.3497,
          23285.6630,  22616.7595,  21967.0709,  21336.0453,  20723.1465,
          20127.8538,  19549.6614,  18988.0782,  18442.6271,  17912.8445,
          17398.2805,  16898.4979,  16413.0720,  15941.5904,  15483.6526,
          15038.8695,  14606.8632,  14187.2667,  13779.7236,  13383.8875,
          12999.4222,  12626.0011,  12263.3068,  11911.0313,  11568.8753,
          11236.5480,  10913.7671,  10600.2585,  10295.7557,  10000.0000])
temp = np.array([290., 300.])

In [3]:
calc.moist_lapse(pres * units.Pa, temp * units.K)

<Quantity([[290.         288.87715469 287.74388929 286.59962584 285.44376255
  284.2756677  283.09468558 281.90013868 280.69132453 279.46751847
  278.22797712 276.9719334  275.69861093 274.40722233 273.09697752
  271.76708801 270.41677761 269.04529295 267.65191297 266.23596587
  264.79684177 263.33401185 261.84704514 260.33563073 258.79959458
  257.23892151 255.65377403 254.04450321 252.41166899 250.75604535
  249.07861963 247.38059138 245.66335952 243.9285067  242.17777231
  240.41302449 238.63622571 236.84939725 235.0545846  233.25381484
  231.44907041 229.64226439 227.83520766 226.02959873 224.22700706
  222.42886837 220.63647635 218.85098916 217.07343112 215.30469869
  213.54556836 211.79670701 210.05867962 208.33196136 206.61694478
  204.91395191 203.22323958 201.54501024 199.879419   198.22657786
  196.58656522 194.95942838 193.34518858 191.74384639 190.15538354
  188.57976728 187.01695141 185.46688002 183.92948945 182.40470603
  180.8924563  179.39265691 177.90522195 176.43006329 174.96709288
  173.51621682 172.07734459 170.65038257 169.23523633 167.8318116 ]
 [300.         299.05736942 298.1112944  297.16152789 296.20781236
  295.24987545 294.28743281 293.32018832 292.34783104 291.37003521
  290.38646029 289.39674565 288.40051583 287.39737584 286.38691213
  285.36868928 284.34225018 283.30711678 282.26278428 281.20872619
  280.14438838 279.06919246 277.98252938 276.88376276 275.77223059
  274.64724055 273.50807139 272.35397929 271.1841901  269.99790546
  268.79430861 267.57256435 266.33182814 265.07124666 263.789974
  262.4871735  261.16203706 259.81379327 258.44172901 257.04520167
  255.62366536 254.17668982 252.70398473 251.20542153 249.68105541
  248.13114539 246.55617732 244.95686782 243.33417111 241.68927963
  240.0236136  238.33880022 236.63665028 234.91912355 233.18829057
  231.44629541 229.69530479 227.93747449 226.17491479 224.40964874
  222.64359591 220.87854549 219.11614518 217.35789405 215.60513845
  213.85907518 212.12075549 210.39109386 208.67087851 206.96077745
  205.2613585  203.57308993 201.89635674 200.23147089 198.57868193
  196.93817955 195.31011011 193.69457669 192.0916471  190.50136017]], 'kelvin')>

In [1]:
import metpy.calc as calc
import metpy._calc_mod as calc_mod
from metpy.units import units
import numpy as np

In [2]:
calc.moist_lapse(np.array([1050., 800., 600., 500., 400.]) * units.mbar,
                       np.array([19.85, 25.6, 19.85]) * units.degC, 1000. * units.mbar).to('kelvin')

<Quantity([[294.76200779 284.63784791 272.80434655 264.40509698 252.88372526]
 [300.35159404 291.26660783 281.04194199 274.03585654 264.62391454]
 [294.76200779 284.63784791 272.80434655 264.40509698 252.88372526]], 'kelvin')>

In [2]:
calc.moist_lapse_linfel(np.array([1050., 800., 600., 500., 400.]) * units.mbar,
                       np.array([19.85, 25.6, 19.85]) * units.degC, 1000. * units.mbar).to('kelvin')

<Quantity([[294.76200779 284.63784791 272.80434655 264.40509698 252.88372526]
 [300.35159404 291.26660783 281.04194199 274.03585654 264.62391454]
 [294.76200779 284.63784791 272.80434655 264.40509698 252.88372526]], 'kelvin')>

In [3]:
calc.moist_lapse_linfel(units.Quantity(1000, 'hPa'), 0 * units.degC, units.Quantity(1000., 'mbar'))


<Quantity([0.], 'degree_Celsius')>

In [5]:
calc.moist_lapse_linfel(np.array([1070,1040]) * units.hPa, 14 * units.degC, np.nan * units.hPa)


<Quantity([nan nan], 'degree_Celsius')>

In [6]:
calc.moist_lapse_linfel(40 * units.hPa, np.nan * units.degC, 400 * units.hPa)

<Quantity([nan], 'degree_Celsius')>